---
- hosts: all
  gather_facts: false
  tasks:
    - name:  wait for SSH to come up
      wait_for_connection: 
        delay: 10
        sleep: 5
        timeout: 300
      vars:
        ansible_user: ec2-user
 #la parte de arriba es una prueba para ver si se espera
 #al ssh para conectar para que no pete.     
- hosts: all
  gather_facts: true
  become: true
  vars:
    ansible_user: ec2-user
  tasks:

    - name: Install docker
      yum: 
        name: docker
        state: latest
    
    - name: Start Docker Service
      service:
        name: docker 
        state: started
        enabled: true

    - name: usermod -a -G docker ec2-user
      user: 
        name: ec2-user
        groups: docker
        append: yes

    - name: Install docker-compose
      pip:
        name: docker-compose
        executable: pip3


    - name: ghcr register
      shell: echo "$CR_PAT | docker login ghcr.io -u VLRuben --password-stdin"

    - name:  wget -> docker-compose 
      shell:
        cmd: wget https://raw.githubusercontent.com/VLRuben/hello-2048/main/docker-compose.yml
        warn: False

   - name: Docker-compose pull {image}
      shell: docker pull ghcr.io/vlruben/hello-2048/hello-2048:latest

  
    - name: docker-compose up -d
      shell: /usr/local/bin/docker-compose up -d

    
