---
- hosts: all
  gather_facts: false
  tasks:
    - name:  wait for SSH to come up
      wait_for_connection: 
        delay: 10
        sleep: 5
        timeout: 300
      vars:
        ansible_user: ec2-user
 #la parte de arriba es una prueba para ver si se espera
 #al ssh para conectar para que no pete.     
- hosts: all
  gather_facts: true
  become: true
  vars:
    ansible_user: ec2-user
  tasks:

    - name: Enable Some packages from amazon-linux-extras packages
      shell: "amazon-linux-extras install -y docker"
    
    - name: Start Docker Service
      service:
        name: docker 
        state: started

    - name: Enable Docker Service
      service:
        name: docker
        state: restarted

    - name: usermod
      shell: "usermod -a -G docker ec2-user"

    - name: Install docker-compose
      shell: "pip3 install docker-compose"

    - name: Docker-compose pull {image}
      shell: docker pull ghcr.io/vlruben/hello-2048/hello-2048:latest

    - name:  wget -> docker-compose 
      shell:
        cmd: wget https://raw.githubusercontent.com/VLRuben/hello-2048/main/docker-compose.yml
        warn: False

    - name: Docker-compose up -d {image}
      shell: docker-compose up -d