---
- hosts: all
  gather_facts: false
  tasks:
    - name:  wait for SSH to come up
      wait_for_connection: 
        delay: 10
        sleep: 5
        timeout: 300
      vars:
        ansible_user: ec2-user
 #la parte de arriba es una prueba para ver si se espera
 #al ssh para conectar para que no pete.     
- hosts: all
  gather_facts: true
  become: true
  vars:
    ansible_user: ec2-user
  tasks:

    - name: Install docker
      yum: 
        name: docker
        state: latest
    
    - name: Start Docker Service
      service:
        name: docker 
        state: started
        enabled: true

    - name: usermod -a -G docker ec2-user
      user: 
        name: ec2-user
        groups: docker
        append: yes

    - name: Install docker-compose
      pip:
        name: docker-compose
        executable: pip3


    - name: ghcr register
      shell: echo "$CR_PAT | docker login ghcr.io -u VLRuben --password-stdin"
    
    - name: docker-compose -> url
      get_url: 
        url: https://raw.githubusercontent.com/VLRuben/hello-terraform/master/docker-compose.yml
        dest: /home/ec2-user
        owner: ec2-user
        group: ec2-user

    - name: docker-compose up 
      docker_compose:
        project_src: /home/ec2-user
        pull: true
      vars:
        ansible_python_interpreter: /usr/bin/python3

    
